"""add_source_pages

Revision ID: 2b5582550d39
Revises: d4a87d3a0ce2
Create Date: 2026-04-28 22:14:32.303767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b5582550d39'
down_revision: Union[str, None] = 'd4a87d3a0ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('page_num', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('image_s3_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sources', sa.Column('status', sa.String(), nullable=False, server_default='done'))
    op.add_column('sources', sa.Column('markdown_s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'markdown_s3_key')
    op.drop_column('sources', 'status')
    op.drop_table('source_pages')
    # ### end Alembic commands ###
